// Generated by CoffeeScript 1.10.0
(function() {
  this.App = new Marionette.Application;

  App.addRegions({
    leftRegion: '#left',
    mainRegion: '#main',
    rightRegion: '#right'
  });

  App.on('initialize:after', function() {
    return Backbone.history.start();
  });

}).call(this);

//# sourceMappingURL=app.js.map
