// Generated by CoffeeScript 1.10.0
(function() {
  var MongoClient, config;

  config = require('../server/config.json');

  MongoClient = require('mongodb').MongoClient;

  MongoClient.connect(config.mongo.uri, config.mongo.options, function(err, db) {
    var generator, i;
    generator = process.argv[2];
    generator = require(__dirname + '/generators/' + generator);
    i = 0;
    return generator(db, {
      increment: function(step) {
        if (step == null) {
          step = 1000;
        }
        i++;
        if (0 === i % step) {
          return console.log(i);
        }
      }
    });
  });

}).call(this);

//# sourceMappingURL=generate.js.map
