// Generated by CoffeeScript 1.10.0
(function() {
  var _, faker;

  faker = require('faker');

  _ = require('underscore');

  module.exports = function(db, $) {
    var conveyor;
    conveyor = [
      {
        $sort: {
          _id: 1
        }
      }, {
        $project: {
          _id: 1
        }
      }, {
        $limit: 100
      }
    ];
    return db.collection('user').aggregate(conveyor, function(err, users) {
      var loop_fn;
      loop_fn = function() {
        var insert_message, sample;
        sample = _.sample(users, _.random(2, users.length));
        insert_message = function() {
          var message, source, target;
          source = sample.pop();
          target = sample.pop();
          if (target) {
            message = {
              source: source._id,
              target: target._id,
              text: faker.lorem.sentences(),
              time: new Date().toISOString()
            };
            return db.collection('message').insertOne(message, function(err, result) {
              if (err) {
                return console.error(err);
              } else {
                $.increment();
                return insert_message();
              }
            });
          } else {
            return loop_fn();
          }
        };
        return insert_message();
      };
      return loop_fn();
    });
  };

}).call(this);

//# sourceMappingURL=message.js.map
