// Generated by CoffeeScript 1.10.0
(function() {
  var _, faker, utils;

  faker = require('faker');

  utils = require('../../server/utils');

  _ = require('underscore');

  module.exports = function(db, $) {
    var aggregation;
    aggregation = [
      {
        $sample: {
          size: 50000
        }
      }
    ];
    return db.collection('user').aggregate(aggregation, function(err, users) {
      var insert_user;
      users = _.map(users, function(u) {
        return u._id;
      });
      insert_user = function() {
        var user;
        user = {
          domain: [faker.internet.domainWord(), _.random(10000, 50000)].join('_'),
          phone: process.hrtime().join(''),
          hash: utils.hash('1')
        };
        if (users.length > 0) {
          user.freind = _.sample(users, _.random(1, 500));
        }
        return db.collection('user').insertOne(user, function(err, result) {
          if (err) {
            console.error(err);
          } else {
            $.increment();
          }
          return insert_user();
        });
      };
      return insert_user();
    });
  };

}).call(this);

//# sourceMappingURL=user.js.map
